# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5


development:
  <<: *default
  database: maintenance_project_dev
  host: localhost
  username: user
  password: password

test:
  <<: *default
  database: maintenance_project_test

production:
  <<: *default
  database: maintenance_project_prod